version: "3"

services:
  web:
    container_name: web
    image: ${CONTAINER_REGISTRY}:web-${TAG}
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile
    # restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
  api-sample:
    container_name: api-sample
    image: ${CONTAINER_REGISTRY}:api-sample-${TAG}
    build:
      context: .
      dockerfile: ./apps/api/template/Dockerfile
    # restart: always
    ports:
      - 5000:5000
    networks:
      - app_network

# Define a network, which allows containers to communicate
# with each other, by using their container name as a hostname
networks:
  app_network:
    name: staycaygowhere-network