name: Build Containers

env:
  src_branch: ${{ github.head_ref || github.ref_name }}
  registry_url: ghcr.io
  org_name: staycaygowhere
  app_name: web

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**"
      - "!.github/workflows/**"

jobs:
  build:
    name: "Build & Upload Container"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3
        with:
          ref: ${{ env.src_branch }}

      - name: "Container Registry Login"
        uses: docker/login-action@v2.1.0
        with:
          registry: ${{ env.registry_url }}
          username: ${{ github.actor }}
          password: ${{ secrets.GH_PAT }}

      # - name: "Configure access to Image Repository"
      #   uses: aws-actions/configure-aws-credentials@v1-node16
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ap-southeast-1

      # - name: "Login to Image Repository"
      #   id: login-ecr
      #   uses: aws-actions/amazon-ecr-login@v1

      - name: "Build & Upload Image"
        id: getImageTag
        run: |
          git_hash=$(git rev-parse --short "$GITHUB_SHA")

          TAG="${{ env.src_branch }}-${git_hash}"

          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "mytag=${TAG}" >> $GITHUB_OUTPUT

          IMAGE_URL="${{ env.registry_url }}/${{ env.org_name }}/${{ env.app_name }}:${TAG}"

          echo "IMAGE_URL=${IMAGE_URL}" >> $GITHUB_ENV

          echo TAG=${TAG} >> .env

          docker compose config
          docker compose build
          docker compose push
